[functions.create-checkout-session]
verify_jwt = false

[functions.update-subscription]
verify_jwt = false

[functions.create-billing-portal]
verify_jwt = false

[functions.invite-user]
verify_jwt = false

[functions.deactivate-user]
verify_jwt = false

[functions.reactivate-user]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
